/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.frame;

import com.controller.ChiNhanhController;
import com.controller.KhachHangController;
import com.models.ChiNhanhModel;
import com.models.DataContext;
import com.models.KhachHangModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DO THAO QUYEN
 */
public class ChiNhanhFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChiNhanhFrame
     */
    public ChiNhanhFrame() {
        initComponents();
        loadTable();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaCN = new javax.swing.JTextField();
        txtTenCN = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btCapNhap = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChiNhanh = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã Chi Nhánh");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 168, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên Chi Nhánh");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 225, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Địa Chỉ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 274, 90, -1));

        txtMaCN.setEnabled(false);
        jPanel2.add(txtMaCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 165, 143, -1));
        jPanel2.add(txtTenCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 219, 143, -1));
        jPanel2.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 271, 143, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Thông tin Chi Nhánh");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 102, -1, -1));

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel2.add(btThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 354, -1, -1));

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 354, -1, -1));

        btCapNhap.setText("Cập Nhập");
        btCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhapActionPerformed(evt);
            }
        });
        jPanel2.add(btCapNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 354, -1, -1));

        btRefresh.setText("Refresh ");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 394, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/background2.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 520));

        tbChiNhanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Chi Nhánh", "Tên Chi Nhánh", "Địa Chỉ"
            }
        ));
        tbChiNhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChiNhanhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbChiNhanh);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Danh sách chi nhánh");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel modelChiNhanh;

    public void loadTable() {
        modelChiNhanh = (DefaultTableModel) new DefaultTableModel();
        try {
            String tieuDe[] = {"Mã Chi Nhánh", "Tên Chi Nhánh", "Địa Chỉ"};
            modelChiNhanh.setColumnIdentifiers(tieuDe);
            Object row[] = new Object[3];
            int i = 0;
            ChiNhanhController.getInstance().LayDuLieu();
            while (i < DataContext.getInstance().getChiNhanhs().size()) {
                row[0] = DataContext.getInstance().getChiNhanhs().get(i).getMaCN();
                row[1] = DataContext.getInstance().getChiNhanhs().get(i).getTenCN();
                row[2] = DataContext.getInstance().getChiNhanhs().get(i).getDiaChi();
                i++;
                modelChiNhanh.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tbChiNhanh.setModel(modelChiNhanh);
        setVisible(true);
    }

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        if (txtTenCN.getText().equals("") || txtDiaChi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Thông tin nhập còn trống", "", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                ChiNhanhModel cn = new ChiNhanhModel();
                cn.setTenCN(txtTenCN.getText());
                cn.setDiaChi(txtDiaChi.getText());
                if (ChiNhanhController.getInstance().ThemChiNhanh(cn) == true) {
                    JOptionPane.showMessageDialog(this, "Thêm chi nhánh thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm chi nhánh không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            loadTable();
            setVisible(true);
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhapActionPerformed
        if (txtTenCN.getText().equals("") || txtDiaChi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Thông tin nhập còn trống", "", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                ChiNhanhModel cn = new ChiNhanhModel();
                int maCN = Integer.parseInt(txtMaCN.getText());
                cn.setMaCN(Integer.parseInt(txtMaCN.getText()));
                cn.setTenCN(txtTenCN.getText());
                cn.setDiaChi(txtDiaChi.getText());
                if (ChiNhanhController.getInstance().SuaChiNhanh(maCN, cn) == true) {
                    JOptionPane.showMessageDialog(this, "Cập nhập chi nhánh thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhập chi nhánh không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            loadTable();
            setVisible(true);
        }
    }//GEN-LAST:event_btCapNhapActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        if (txtMaCN.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn chi nhánh để xóa", "Thông báo", 1);
        } else {
            try {
                int result = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa chi nhánh này", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    if (ChiNhanhController.getInstance().XoaChiNhanh(Integer.parseInt(txtMaCN.getText())) == true) {
                        JOptionPane.showMessageDialog(this, "Xóa chi nhánh thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa chi nhánh không thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                loadTable();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void tbChiNhanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChiNhanhMouseClicked
        try {
            int row = this.tbChiNhanh.getSelectedRow();
            if (row >= 0 && row <= tbChiNhanh.getRowCount()) {
                txtMaCN.setText(tbChiNhanh.getValueAt(row, 0).toString());
                txtTenCN.setText(tbChiNhanh.getValueAt(row, 1).toString());
                txtDiaChi.setText(tbChiNhanh.getValueAt(row, 2).toString());
            }
            loadTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbChiNhanhMouseClicked

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        txtMaCN.setText("");
        txtTenCN.setText("");
        txtDiaChi.setText("");
    }//GEN-LAST:event_btRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhap;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbChiNhanh;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaCN;
    private javax.swing.JTextField txtTenCN;
    // End of variables declaration//GEN-END:variables
}
