/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.frame;

import com.controller.DoUongController;
import com.handle.ImageHandle;
import com.handle.LanguageHandle;
import com.models.DataContext;
import com.models.DoUongModel;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dang
 */
public class DoUongFrame extends javax.swing.JFrame {

    DefaultTableModel modelttKH;

    /**
     * Creates new form KhachHangFrame
     */
    public DoUongFrame() {
        initComponents();
        loadTable();
        loadText();
        configComponents();
    }

    private void loadText() {
        TITLE = LanguageHandle.getInstance().getValue("Drink", "TITLE");
        UPDATE = LanguageHandle.getInstance().getValue("Drink", "UPDATE");
        RESET = LanguageHandle.getInstance().getValue("Drink", "RESET");
        EXIT = LanguageHandle.getInstance().getValue("Drink", "EXIT");
        REFRESH = LanguageHandle.getInstance().getValue("Drink", "REFRESH");
        DELETE = LanguageHandle.getInstance().getValue("Drink", "DELETE");
        NOTE = LanguageHandle.getInstance().getValue("Drink", "NOTE");
        PRICE = LanguageHandle.getInstance().getValue("Drink", "PRICE");
        IMAGE = LanguageHandle.getInstance().getValue("Drink", "IMAGE");
        INFO = LanguageHandle.getInstance().getValue("Drink", "INFO");
        ID = LanguageHandle.getInstance().getValue("Drink", "ID");
        NAME = LanguageHandle.getInstance().getValue("Drink", "NAME");
        ERR_NAME_EMPTY = LanguageHandle.getInstance().getValue("Drink", "ERR_NAME_EMPTY");
        ERR_PRICE_EMPTY = LanguageHandle.getInstance().getValue("Drink", "ERR_PRICE_EMPTY");
        NOTIFICATION_TITLE = LanguageHandle.getInstance().getValue("Drink", "NOTIFICATION_TITLE");
        NOTI_SUCCESS = LanguageHandle.getInstance().getValue("Drink", "NOTI_SUCCESS");
        NOTI_FAILED = LanguageHandle.getInstance().getValue("Drink", "NOTI_FAILED");
        CHOSSE_DELETE = LanguageHandle.getInstance().getValue("Drink", "CHOSSE_DELETE");
        REQUEST_DELETE = LanguageHandle.getInstance().getValue("Drink", "REQUEST_DELETE");
    }

    private void configComponents() {
        setIconImage(ImageHandle.getInstance().getIconLogo());
        setTitle(TITLE);
        btnCapNhap.setText(UPDATE);
        btnReset.setText(RESET);
        btnCapNhap.setText(REFRESH);
        btnXoa.setText(DELETE);

        lbGhiChu.setText(NOTE);
        lbGia.setText(PRICE);
        lbHinhAnh.setText(IMAGE);
        lbInfo.setText(INFO);
        lbMaDU.setText(ID);
        lbTenDU.setText(NAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinDU = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbMaDU = new javax.swing.JLabel();
        lbTenDU = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        lbHinhAnh = new javax.swing.JLabel();
        txtMaDU = new javax.swing.JTextField();
        txtTenDU = new javax.swing.JTextField();
        lbInfo = new javax.swing.JLabel();
        lbGhiChu = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        lbIcon = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbThongTinDU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Đồ Uống ", "Tên Đồ Uống ", "Giá ", "Ghi Chú"
            }
        ));
        tbThongTinDU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinDUMouseClicked(evt);
            }
        });
        tbThongTinDU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbThongTinDUKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinDU);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        lbMaDU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMaDU.setText("Mã Đồ Uống ");

        lbTenDU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTenDU.setText("Tên Đồ Uống ");

        lbGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGia.setText("Giá");

        lbHinhAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHinhAnh.setText("Hình Ảnh ");

        txtMaDU.setEditable(false);
        txtMaDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDUActionPerformed(evt);
            }
        });

        lbInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbInfo.setText("THÔNG TIN ĐỒ UỐNG");

        lbGhiChu.setText("Ghi Chú");

        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/logo.png"))); // NOI18N

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/add (1).png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/delete (1).png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/edit (2).png"))); // NOI18N
        btnCapNhap.setText("Cập Nhập");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/refresh-arrow.png"))); // NOI18N
        btnReset.setText("Refresh");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbInfo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaDU)
                            .addComponent(lbTenDU)
                            .addComponent(lbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGhiChu)
                            .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDU, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaDU, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCapNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbInfo)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaDU))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTenDU)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGia))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGhiChu)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbHinhAnh))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel modelThongTinDU;

    public void loadTable() {
        modelThongTinDU = new DefaultTableModel();
        String tieuDe[] = {ID, NAME, PRICE, NOTE};
        modelThongTinDU.setColumnIdentifiers(tieuDe);
        Object row[] = new Object[4];
        DoUongController.getInstance().LayDuLieu();
        int i = 0;
        while (i < DataContext.getInstance().getDoUongs().size()) {
            try {
                row[0] = DataContext.getInstance().getDoUongs().get(i).getMaDU();
                row[1] = DataContext.getInstance().getDoUongs().get(i).getTenDU();
                row[2] = DataContext.getInstance().getDoUongs().get(i).getGia();
                row[3] = DataContext.getInstance().getDoUongs().get(i).getGhiChu();
                i++;
                modelThongTinDU.addRow(row);
            } catch (Exception e) {
            }
        }
        tbThongTinDU.setModel(modelThongTinDU);
        setVisible(true);
    }

    public String checkError() {
        if (txtTenDU.getText().equals("")) {
            return ERR_NAME_EMPTY;
        }
        if (txtGia.getText().equals("")) {
            return ERR_PRICE_EMPTY;
        }
        return "";
    }
    private void tbThongTinDUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbThongTinDUKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbThongTinDUKeyPressed

    private void tbThongTinDUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinDUMouseClicked
        try {
            int row = this.tbThongTinDU.getSelectedRow();
            if (row >= 0 && row <= tbThongTinDU.getRowCount()) {
                txtMaDU.setText(tbThongTinDU.getValueAt(row, 0).toString());
                txtTenDU.setText(tbThongTinDU.getValueAt(row, 1).toString());
                txtGia.setText(tbThongTinDU.getValueAt(row, 2).toString());
                txtGhiChu.setText(tbThongTinDU.getValueAt(row, 4).toString());
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbThongTinDUMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtMaDU.setText("");
        txtTenDU.setText("");
        txtGia.setText("");
        txtGhiChu.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        StringBuilder sb = new StringBuilder();
        var x = checkError();
        if (!x.equals("")) {
            JOptionPane.showConfirmDialog(null, x, NOTIFICATION_TITLE, JOptionPane.DEFAULT_OPTION);
            return;
        }
        try {
            DoUongModel doUongModel = new DoUongModel();
            doUongModel.setTenDU(txtTenDU.getText());
            doUongModel.setGia(Double.parseDouble(txtGia.getText()));
            if ("".equals(txtGhiChu.getText())) {
                return;
            } else {
                doUongModel.setGhiChu(txtGhiChu.getText());
            }

            if (DoUongController.getInstance().SuaDoUong(Integer.parseInt(txtMaDU.getText()), doUongModel) == true) {
                JOptionPane.showMessageDialog(this, NOTI_SUCCESS, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
            }
            loadTable();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (this.txtMaDU.getText().equals(""))
            JOptionPane.showMessageDialog(null, CHOSSE_DELETE, NOTIFICATION_TITLE, 1);
        else {
            try {
                int result = JOptionPane.showConfirmDialog(this, REQUEST_DELETE, NOTIFICATION_TITLE, JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    if (DoUongController.getInstance().XoaDoUong(Integer.parseInt(txtMaDU.getText())) == true) {
                        JOptionPane.showMessageDialog(this, NOTI_SUCCESS, NOTIFICATION_TITLE, JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.WARNING_MESSAGE);
                    }
                }
                loadTable();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        var x = checkError();
        if (!x.equals("")) {
            JOptionPane.showConfirmDialog(null, x, NOTIFICATION_TITLE, JOptionPane.DEFAULT_OPTION);
            return;
        }
        try {
            DoUongModel doUongModel = new DoUongModel();
            doUongModel.setTenDU(txtTenDU.getText());
            doUongModel.setGia(Double.parseDouble(txtGia.getText()));
            if ("".equals(txtGhiChu.getText())) {
                return;
            } else {
                doUongModel.setGhiChu(txtGhiChu.getText());
            }
            if (DoUongController.getInstance().ThemDoUong(doUongModel) == true) {
                JOptionPane.showMessageDialog(this, NOTI_SUCCESS, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
            }
            loadTable();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void txtMaDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDUActionPerformed

    //Text
    private String TITLE;
    private String UPDATE;
    private String RESET;
    private String EXIT;
    private String REFRESH;
    private String DELETE;
    private String NOTE;
    private String PRICE;
    private String IMAGE;
    private String INFO;
    private String ID;
    private String NAME;
    private String ERR_NAME_EMPTY;
    private String ERR_PRICE_EMPTY;
    private String NOTIFICATION_TITLE;
    private String NOTI_SUCCESS;
    private String NOTI_FAILED;
    private String CHOSSE_DELETE;
    private String REQUEST_DELETE;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGhiChu;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbHinhAnh;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbMaDU;
    private javax.swing.JLabel lbTenDU;
    private javax.swing.JTable tbThongTinDU;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaDU;
    private javax.swing.JTextField txtTenDU;
    // End of variables declaration//GEN-END:variables
}
