/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.frame;

import com.controller.KhachHangController;
import com.handle.ImageHandle;
import com.models.DataContext;
import com.models.KhachHangModel;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DO THAO QUYEN
 */
public class KhachHangFrame extends javax.swing.JFrame {

    DefaultTableModel modelttKH;

    /**
     * Creates new form KhachHangFrame
     */
    public KhachHangFrame() {
        initComponents();
        loadTable();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinKH = new javax.swing.JTable();
        lbDSKhachHang = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbSDT = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbTongDiem = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox<>();
        txtTongDiem = new javax.swing.JTextField();
        lbTTKhachHang = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        btCapNhap = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbThongTinKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số Điện Thoại", "Tên Khách Hàng", "Giới Tính", "Tổng Điểm"
            }
        ));
        tbThongTinKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinKHMouseClicked(evt);
            }
        });
        tbThongTinKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbThongTinKHKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinKH);

        lbDSKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDSKhachHang.setText("Danh sách Khách Hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbDSKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDSKhachHang)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSDT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSDT.setText("Số Điện Thoại");
        jPanel3.add(lbSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lbTenKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTenKH.setText("Tên Khách Hàng");
        jPanel3.add(lbTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lbGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGioiTinh.setText("Giới Tính");
        jPanel3.add(lbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));

        lbTongDiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTongDiem.setText("Tổng Điểm");
        jPanel3.add(lbTongDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, -1));
        jPanel3.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 156, -1));
        jPanel3.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 156, -1));

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel3.add(cbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));
        jPanel3.add(txtTongDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 156, -1));

        lbTTKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTTKhachHang.setText("THÔNG TIN KHÁCH HÀNG");
        jPanel3.add(lbTTKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/add (1).png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel3.add(btThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 30));

        btCapNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/edit (2).png"))); // NOI18N
        btCapNhap.setText("Cập Nhập");
        btCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhapActionPerformed(evt);
            }
        });
        jPanel3.add(btCapNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 30));

        btXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/delete (1).png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, 30));

        btReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/refresh-arrow.png"))); // NOI18N
        btReset.setText("Refresh");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        jPanel3.add(btReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 100, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/background2.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 490));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String checkError() {
        if (txtSDT.getText().equals("")) {
            return "Số điện thoại còn trống";
        } else {
            try {
                Integer.parseInt(txtSDT.getText());
            } catch (Exception e) {
                return "Số điện thoại không hợp lệ!";
            }
        }
        if (txtSDT.getText().length() < 9 || txtSDT.getText().length() > 11) {
            return "Số điện thoại hợp lệ";
        }

        if (txtTenKH.getText().equals("")) {
            return "Tên khách hàng còn trống";
        }
        if (txtTongDiem.getText().equals("")) {
            try {
                int tongdiem = Integer.parseInt(txtTongDiem.getText());
                if (tongdiem < 0) {
                    return "Tổng điểm không hợp lệ";
                }
            } catch (Exception e) {
                return "Tổng điểm không hợp lệ";
            }
            return "Tổng điểm còn trống";
        }
        return "";
    }

    public void loadTable() {
        modelttKH = (DefaultTableModel) new DefaultTableModel();
        try {
            KhachHangModel kh = new KhachHangModel();
            modelttKH = new DefaultTableModel();
            String tieuDe[] = {"Số Điện Thoại", "Tên Khách Hàng", "Giới Tính", "Tổng Điểm"};
            modelttKH.setColumnIdentifiers(tieuDe);
            Object row[] = new Object[4];
            int i = 0;
            KhachHangController.getInstance().LayDuLieu();
            while (i < DataContext.getInstance().getKhachHangs().size()) {
                row[0] = DataContext.getInstance().getKhachHangs().get(i).getSDTKH();
                row[1] = DataContext.getInstance().getKhachHangs().get(i).getTenKH();
                int gt = DataContext.getInstance().getKhachHangs().get(i).getGioiTinh();
                if (gt == 0) {
                    row[2] = "Nam";
                } else {
                    row[2] = "Nữ";
                }
                row[3] = DataContext.getInstance().getKhachHangs().get(i).getTongDiem();
                i++;
                modelttKH.addRow(row);
            }
        } catch (Exception e) {
        }
        tbThongTinKH.setModel(modelttKH);
        setVisible(true);
    }

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        String sdt = txtSDT.getText();
        String tenKH = txtTenKH.getText();
        StringBuilder sb = new StringBuilder();
        var x = checkError();
        if (!x.equals("")) {
            JOptionPane.showConfirmDialog(null, x, "title", JOptionPane.DEFAULT_OPTION);
            return;
        }
        try {
            KhachHangModel kh = new KhachHangModel();
            kh.setSDTKH(sdt);
            kh.setTenKH(tenKH);
            //0: Nam 1: Nữ
            if (cbGioiTinh.getSelectedItem().equals("Nam")) {
                kh.setGioiTinh(0);
            } else {
                kh.setGioiTinh(1);
            }
            kh.setTongDiem(Integer.parseInt(txtTongDiem.getText()));
            if (KhachHangController.getInstance().SuaKhachHang(sdt, kh) == true) {
                JOptionPane.showMessageDialog(null, "Thêm khách hàng thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Thêm khách hàng không thành công");
            }
            loadTable();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhapActionPerformed
        String tenKH = txtTenKH.getText();
        txtSDT.setEditable(true);
        StringBuilder sb = new StringBuilder();
        var x = checkError();
        if (!x.equals("")) {
            JOptionPane.showConfirmDialog(null, x, "title", JOptionPane.DEFAULT_OPTION);
            return;
        }
        try {
            KhachHangModel kh = new KhachHangModel();
            kh.setTenKH(tenKH);
            //0: Nam 1: Nữ
            if (cbGioiTinh.getSelectedItem().equals("Nam")) {
                kh.setGioiTinh(0);
            } else {
                kh.setGioiTinh(1);
            }
            kh.setTongDiem(Integer.parseInt(txtTongDiem.getText()));
            if (KhachHangController.getInstance().SuaKhachHang(txtSDT.getText(), kh) == true) {
                JOptionPane.showMessageDialog(null, "Cập nhập khách hàng thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhập khách hàng không thành công");
            }
            loadTable();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btCapNhapActionPerformed

    private void tbThongTinKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbThongTinKHKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbThongTinKHKeyPressed

    private void tbThongTinKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinKHMouseClicked
        try {
            int row = this.tbThongTinKH.getSelectedRow();
            if (row >= 0 && row <= tbThongTinKH.getRowCount()) {
                txtSDT.setText(tbThongTinKH.getValueAt(row, 0).toString());
                txtTenKH.setText(tbThongTinKH.getValueAt(row, 1).toString());
                if (tbThongTinKH.getValueAt(row, 2).toString().trim().equals("0")) {
                    cbGioiTinh.setSelectedItem("Nam");
                } else {
                    cbGioiTinh.setSelectedItem("Nữ");
                }
                txtTongDiem.setText(tbThongTinKH.getValueAt(row, 3).toString());
            }
            loadTable();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbThongTinKHMouseClicked

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        txtSDT.setText("");
        txtTenKH.setText("");
        txtTongDiem.setText("");
        cbGioiTinh.setSelectedIndex(0);
    }//GEN-LAST:event_btResetActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        if (this.txtSDT.getText().length() == 0)
            JOptionPane.showMessageDialog(null, "Bạn cần chọn số điện thoại để xóa", "Thông báo", 1);
        else {
            try {
                int result = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa khách hàng này", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    if (KhachHangController.getInstance().XoaKhachHang(txtSDT.getText()) == true) {
                        JOptionPane.showMessageDialog(this, "Xóa khách hàng thành công", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa không thành công!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    }
                }
                loadTable();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhap;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDSKhachHang;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTTKhachHang;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTongDiem;
    private javax.swing.JTable tbThongTinKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTongDiem;
    // End of variables declaration//GEN-END:variables
}
