/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.frame;

import com.controller.KhachHangController;
import com.controller.NhanVienController;
import com.models.DataContext;
import com.models.NhanVienModel;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DO THAO QUYEN
 */
public class NhanVienFrame extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangFrame01
     */
    public NhanVienFrame() {
        initComponents();
        LoadTable();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTenCN = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btCapNhap = new javax.swing.JButton();
        btRefreshNV = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbMaCN = new javax.swing.JComboBox<>();
        NgayVL = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNV = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mã Chi Nhánh");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 157, 85, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã Nhân Viên");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 101, 85, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tên Nhân Viên");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 253, 85, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Giới Tính");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 303, 82, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ngày Vào Làm");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 355, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CCCD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 400, 82, -1));

        txtMaNV.setEnabled(false);
        jPanel2.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 98, 146, -1));

        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });
        jPanel2.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 146, -1));

        txtCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCCDActionPerformed(evt);
            }
        });
        jPanel2.add(txtCCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 397, 143, -1));

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel2.add(cbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tên Chi Nhánh");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 205, 85, -1));

        txtTenCN.setEnabled(false);
        jPanel2.add(txtTenCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 202, 146, -1));

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel2.add(btThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 448, -1, -1));

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        btCapNhap.setText("Cập Nhập");
        btCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhapActionPerformed(evt);
            }
        });
        jPanel2.add(btCapNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 448, -1, -1));

        btRefreshNV.setText("Refresh ");
        btRefreshNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshNVActionPerformed(evt);
            }
        });
        jPanel2.add(btRefreshNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 488, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Thông tin Nhân Viên");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 41, -1, -1));

        cbMaCN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cbMaCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaCNActionPerformed(evt);
            }
        });
        jPanel2.add(cbMaCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 154, -1, -1));
        jPanel2.add(NgayVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 349, 143, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/background2.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 550));

        tbNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Chi Nhánh", "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Vào Làm", "CCCD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNV);

        jLabel11.setText("Danh sach nhan vien");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel listNV;

    public void LoadTable() {
        listNV = new DefaultTableModel();
        String tieuDe[] = {"Mã Chi Nhánh", "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Vào Làm", "CCCD"};
        listNV.setColumnIdentifiers(tieuDe);
        Object row[] = new Object[6];
        NhanVienController.getInstance().LayDuLieu();
        int i = 0;
        while (i < DataContext.getInstance().getNhanViens().size()) {
            try {
                row[0] = DataContext.getInstance().getNhanViens().get(i).getMaCN();
                row[1] = DataContext.getInstance().getNhanViens().get(i).getMaNV();
                row[2] = DataContext.getInstance().getNhanViens().get(i).getTenNV();
                row[3] = DataContext.getInstance().getNhanViens().get(i).getGioiTinh();
                row[4] = DataContext.getInstance().getNhanViens().get(i).getNgayVL();
                row[5] = DataContext.getInstance().getNhanViens().get(i).getCCCD();
                i++;
                listNV.addRow(row);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tbNV.setModel(listNV);
        setVisible(true);
    }

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        String tenNV = txtTenNV.getText();
        String cccd = txtCCCD.getText();

        if (tenNV.length() == 0 || cccd.length() == 0) {
            JOptionPane.showMessageDialog(this, "Thông tin còn trống", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                NhanVienModel nv = new NhanVienModel();
                nv.setTenNV(tenNV);
                //1. UIT 2. Trung tâm 3. Miền Bắc
                if (cbMaCN.getSelectedItem().equals("1")) {
                    nv.setMaCN(1);
                } else if (cbMaCN.getSelectedItem().equals("2")) {
                    nv.setMaCN(2);
                } else {
                    nv.setMaCN(3);
                }
                nv.setCCCD(cccd);
                //Nam: 0, Nữ: 1
                if (cbGioiTinh.getSelectedItem().equals("Nam")) {
                    nv.setGioiTinh(0);
                } else {
                    nv.setGioiTinh(1);
                }
                nv.setNgayVL(NgayVL.getDate());
                if (NhanVienController.getInstance().ThemNhanVien(nv) == true) {
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
                LoadTable();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void cbMaCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaCNActionPerformed
        try {
            txtTenCN.setText(NhanVienController.getInstance().hienthiTenCN((Integer.parseInt(cbMaCN.getSelectedItem().toString()))));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbMaCNActionPerformed

    private void btCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhapActionPerformed
        String tenNV = txtTenNV.getText();
        String cccd = txtCCCD.getText();

        if (tenNV.length() == 0 || cccd.length() == 0 || NgayVL.getDateFormatString().equals("")) {
            JOptionPane.showMessageDialog(this, "Thông tin còn trống", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                NhanVienModel nv = new NhanVienModel();
                nv.setTenNV(tenNV);
                //1. UIT 2. Trung tâm 3. Miền Bắc
                if (cbMaCN.getSelectedItem().equals("1")) {
                    nv.setMaCN(1);
                } else if (cbMaCN.getSelectedItem().equals("2")) {
                    nv.setMaCN(2);
                } else {
                    nv.setMaCN(3);
                }
                nv.setCCCD(cccd);
                //Nam: 0, Nữ: 1
                if (cbGioiTinh.getSelectedItem().equals("Nam")) {
                    nv.setGioiTinh(0);
                } else {
                    nv.setGioiTinh(1);
                }
                nv.setNgayVL(NgayVL.getDate());
                int maNV = Integer.parseInt(txtMaNV.getText());
                if (NhanVienController.getInstance().SuaNhanVien(maNV, nv) == true) {
                    JOptionPane.showMessageDialog(this, "Cập nhập nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhập nhân viên không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
                LoadTable();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btCapNhapActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        NhanVienController.getInstance().LayDuLieu();
        int maNV = Integer.parseInt(txtMaNV.getText());
        if (maNV == 0)
            JOptionPane.showMessageDialog(null, "Bạn cần chọn nhân viên để xóa", "Thông báo", 1);
        else {
            try {
                int result = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa nhân viên này", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    if (NhanVienController.getInstance().XoaNhanVien(maNV) == true) {
                        JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa nhân viên không thành công!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    }
                }
                LoadTable();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btRefreshNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshNVActionPerformed
        cbMaCN.setSelectedIndex(0);
        txtTenNV.setText("");
        txtCCCD.setText("");
        cbGioiTinh.setSelectedIndex(0);
        txtTenCN.setText("");
        txtMaNV.setText("");
        NgayVL.setDateFormatString("");
    }//GEN-LAST:event_btRefreshNVActionPerformed

    private void tbNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNVMouseClicked
        try {
            int row = this.tbNV.getSelectedRow();
            if (row >= 0 && row <= tbNV.getRowCount()) {
                txtMaNV.setText(tbNV.getValueAt(row, 1).toString());
                cbMaCN.setSelectedIndex(Integer.parseInt(tbNV.getValueAt(row, 0).toString()));
                txtTenNV.setText(tbNV.getValueAt(row, 2).toString());
                //0: Nam 1: Nữ
                cbGioiTinh.setSelectedIndex(Integer.parseInt(tbNV.getValueAt(row, 3).toString()));
                NgayVL.setDate(new SimpleDateFormat("yyyy-mm-dd").parse(tbNV.getValueAt(row, 4).toString()));
                txtCCCD.setText(tbNV.getValueAt(row, 5).toString());
                LoadTable();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbNVMouseClicked

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser NgayVL;
    private javax.swing.JButton btCapNhap;
    private javax.swing.JButton btRefreshNV;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbMaCN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tbNV;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTenCN;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
