/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.frame;

import com.controller.HoaDonKhachHangController;
import com.models.DataContext;
import com.models.HoaDonKhachHangModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ThongKeFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeFrame
     */
    public ThongKeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        month = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        thongke = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HoaDontb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        thongke.setText("Thong ke");
        thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongkeActionPerformed(evt);
            }
        });

        HoaDontb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa đơn ", "Mã Giảm giá ", "SĐT Khách hàng ", "Mã Nhân viên ", "Ngày lập ", "Tổng tiền "
            }
        ));
        jScrollPane1.setViewportView(HoaDontb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(77, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thongke)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thongke)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongkeActionPerformed
        int month = Integer.getInteger(this.month.getText());
        int year = Integer.getInteger(this.year.getText());
        if (month == 0 || year == 0) {
            JOptionPane.showMessageDialog(this, "thang va nam khong duoc de trong!!");
        } else
            try {
            HoaDonKhachHangController.getInstance().ThongKe(month, year);

        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_thongkeActionPerformed

    /**
     * @param args the command line arguments
     */

    public void LoadTable() {
        DefaultTableModel modelHDKH = (DefaultTableModel) new DefaultTableModel();

        try {
            HoaDonKhachHangModel kh = new HoaDonKhachHangModel();
            String tieuDe[] = {"Mã Hóa don", "Ngày lap", "Tong tien"};
            modelHDKH.setColumnIdentifiers(tieuDe);
            Object row[] = new Object[5];
            int i = 0;
            HoaDonKhachHangController.getInstance().LayDuLieu();
            while (i < DataContext.getInstance().getHoaDonKhachHangs().size()) {
                row[0] = DataContext.getInstance().getHoaDonKhachHangs().get(i).getMaHD();
                row[1] = DataContext.getInstance().getHoaDonKhachHangs().get(i).getMaGiamGia();
                row[2] = DataContext.getInstance().getHoaDonKhachHangs().get(i).getSDTKH();
                row[3] = DataContext.getInstance().getHoaDonKhachHangs().get(i).getMaNV();
                row[4] = DataContext.getInstance().getHoaDonKhachHangs().get(i).getNgayLap();
                row[5] = DataContext.getInstance().getHoaDonKhachHangs().get(i).getTongTien();
                i++;
                modelHDKH.addRow(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        HoaDontb.setModel(modelHDKH);

        setVisible(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HoaDontb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField month;
    private javax.swing.JButton thongke;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
